# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KeL1Y4-KAm4qdB-4UIQEWOgOEFQdCMD3
"""


import streamlit as st
import pandas as pd
import joblib


model = joblib.load('predictive_maintenance_model.pkl')


st.title("Predictive Maintenance Dashboard")
st.write("""
This application uses a Machine Learning model to predict the probability of machine failure
based on real-time sensor data.
""")

st.sidebar.header("Sensor Input Data")


def user_input_features():
    m_type = st.sidebar.selectbox("Machine Quality Type", ["L", "M", "H"])
    air_temp = st.sidebar.number_input("Air temperature [K]", min_value=200.0, max_value=400.0, value=300.0)
    proc_temp = st.sidebar.number_input("Process temperature [K]", min_value=200.0, max_value=400.0, value=310.0)
    rpm = st.sidebar.number_input("Rotational speed [rpm]", min_value=0.0, max_value=5000.0, value=1500.0)
    torque = st.sidebar.number_input("Torque [Nm]", min_value=0.0, max_value=100.0, value=40.0)
    tool_wear = st.sidebar.number_input("Tool wear [min]", min_value=0.0, max_value=500.0, value=0.0)

    data = {
        'Type': m_type,
        'Air temperature [K]': air_temp,
        'Process temperature [K]': proc_temp,
        'Rotational speed [rpm]': rpm,
        'Torque [Nm]': torque,
        'Tool wear [min]': tool_wear
    }
    return pd.DataFrame([data])

input_df = user_input_features()

# Display the input parameters to the user
st.subheader("Current Sensor Readings")
st.write(input_df)

# Prediction Logic
if st.button("Analyze Machine Status"):
    # Perform prediction
    prediction = model.predict(input_df)
    probability = model.predict_proba(input_df)[0][1]

    st.subheader("Diagnostic Results")

    if prediction[0] == 1:
        st.error(f"⚠️ **Warning:** High risk of failure detected!")
        st.write(f"Confidence Level: **{probability:.2%}**")
        st.write("Action Required: Immediate maintenance inspection suggested.")
    else:
        st.success(f"✅ **Normal:** Machine is operating within safe parameters.")
        st.write(f"Probability of failure: **{probability:.2%}**")
        st.write("Action Required: Continue standard monitoring.")

# Footer
st.markdown("---")
st.caption("Model trained on AI4I 2020 Predictive Maintenance Dataset.")

